Schema.voice = { normalVoice = { }, dispatchVoice = { } }

local combine = { "mpf", "ota" }

function Schema.voice.AddVoice( faction, command, output, sound )
	Schema.voice.normalVoice[ #Schema.voice.normalVoice + 1 ] = {
		faction = faction,
		command = command,
		output = output,
		sound = sound
	}
end

function Schema.voice.AddDispatch( command, output, sound )
	Schema.voice.dispatchVoice[ #Schema.voice.dispatchVoice + 1 ] = {
		command = command,
		output = output,
		sound = sound
	}
end

Schema.voice.AddDispatch( "Anti-Citizen", "Attention ground units. Anti-citizen reported in this community. Code: LOCK, CAUTERIZE, STABILIZE.", "npc/overwatch/cityvoice/f_anticitizenreport_spkr.wav" )
Schema.voice.AddDispatch( "Anti-Civil", "Protection team alert. Evidence of anti-civil activity in this community. Code: ASSEMBLE, PLAN, CONTAIN.", "npc/overwatch/cityvoice/f_anticivilevidence_3_spkr.wav" )
Schema.voice.AddDispatch( "Person Interest", "Attention please. Unidentified person of interest confirm your civil status with local protection team immediately.", "npc/overwatch/cityvoice/f_confirmcivilstatus_1_spkr.wav" )
Schema.voice.AddDispatch( "Citizen Inaction", "Citizen reminder. Inaction is conspiracy. Report counter behaviour to a Civil Protection team immediately.", "npc/overwatch/cityvoice/f_innactionisconspiracy_spkr.wav" )
Schema.voice.AddDispatch( "Unrest Structure", "Alert community ground protection units, local unrest structure detected. ASSEMBLE, ADMINISTER, PACIFY.", "npc/overwatch/cityvoice/f_localunrest_spkr.wav" )
Schema.voice.AddDispatch( "Status Evasion", "Attention protection team. Status evasion in progress in this community. RESPOND, ISOLATE, ENQUIRE.", "npc/overwatch/cityvoice/f_protectionresponse_1_spkr.wav" )
Schema.voice.AddDispatch( "Lockdown", "Attention all ground protection teams. Judgment waiver now in effect. Capital prosecution is discretionary.", "npc/overwatch/cityvoice/f_protectionresponse_5_spkr.wav" )
Schema.voice.AddDispatch( "Rations Deducted", "Attention occupants. Your block is now charged with permissive inactive cohesion. Five ration units deducted.", "npc/overwatch/cityvoice/f_rationunitsdeduct_3_spkr.wav" )
Schema.voice.AddDispatch( "Inspection", "Citizen notice. Priority identification check in progress. Please assemble in your designated inspection positions.", "npc/overwatch/cityvoice/f_trainstation_assemble_spkr.wav" )
Schema.voice.AddDispatch( "Inspection 2", "Attention please. All citizens in local residential block, assume your inspection positions.", "npc/overwatch/cityvoice/f_trainstation_assumepositions_spkr.wav" )
Schema.voice.AddDispatch( "Miscount Detected", "Attention resident. Miscount detected in your block. Co-operation with your Civil Protection team permit full ration reward.", "npc/overwatch/cityvoice/f_trainstation_cooperation_spkr.wav" )
Schema.voice.AddDispatch( "Infection", "Attention resident. This block contains potential civil infection. INFORM, CO-OPERATE, ASSEMBLE.", "npc/overwatch/cityvoice/f_trainstation_inform_spkr.wav" )
Schema.voice.AddDispatch( "Relocation", "Citizen notice. Failure to co-operate will result in permanent off-world relocation.", "npc/overwatch/cityvoice/f_trainstation_offworldrelocation_spkr.wav" )
Schema.voice.AddDispatch( "Unrest Code", "Attention community. Unrest procedure code is now in effect. INOCULATE, SHIELD, PACIFY. Code: PRESSURE, SWORD, STERILIZE.", "npc/overwatch/cityvoice/f_unrestprocedure1_spkr.wav" )
Schema.voice.AddDispatch( "Evasion", "Attention please. Evasion behaviour consistent with mal-compliant defendant. Ground protection team, alert. Code: ISOLATE, EXPOSE, ADMINISTER.", "npc/overwatch/cityvoice/f_evasionbehavior_2_spkr.wav" )
Schema.voice.AddDispatch( "Individual", "Individual. You are charged with social endangerment, level one. Protection unit, prosecution code: DUTY, SWORD, MIDNIGHT.", "npc/overwatch/cityvoice/f_sociolevel1_4_spkr.wav" )
Schema.voice.AddDispatch( "Autonomous", "Attention all ground protection teams. Autonomous judgement is now in effect, sentencing is now discretionary. Code: AMPUTATE, ZERO, CONFIRM.", "npc/overwatch/cityvoice/f_protectionresponse_4_spkr.wav" )
Schema.voice.AddDispatch( "Citizenship", "Individual. You are convicted of multi anti-civil violations. Implicit citizenship revoked. Status: MALIGNANT.", "npc/overwatch/cityvoice/f_citizenshiprevoked_6_spkr.wav" )
Schema.voice.AddDispatch( "Malcompliance", "Individual. You are charged with capital malcompliance, anti-citizen status approved.", "npc/overwatch/cityvoice/f_capitalmalcompliance_spkr.wav" )
Schema.voice.AddDispatch( "Exogen", "Overwatch acknowledges critical exogen breach, AirWatch augmentation force dispatched and inbound. Hold for reinforcements.", "npc/overwatch/cityvoice/fprison_airwatchdispatched.wav" )
Schema.voice.AddDispatch( "Failure", "Attention ground units. Mission failure will result in permanent off-world assignment. Code reminder: SACRIFICE, COAGULATE, PLAN.", "npc/overwatch/cityvoice/fprison_missionfailurereminder.wav" )

Schema.voice.AddVoice( combine, "Sweeping", "Sweeping for suspect.", "npc/metropolice/hiding02.wav" )
Schema.voice.AddVoice( combine, "Isolate", "Isolate!", "npc/metropolice/hiding05.wav" )
Schema.voice.AddVoice( combine, "You Can Go", "Alright, you can go.", "npc/metropolice/vo/allrightyoucango.wav" )
Schema.voice.AddVoice( combine, "Need Assistance", "Eleven-ninety-nine, officer needs assistance!", "npc/metropolice/vo/11-99officerneedsassistance.wav" )
Schema.voice.AddVoice( combine, "Administer", "Administer.", "npc/metropolice/vo/administer.wav" )
Schema.voice.AddVoice( combine, "Affirmative", "Affirmative.", "npc/metropolice/vo/affirmative.wav" )
Schema.voice.AddVoice( combine, "All Units Move In", "All units move in!", "npc/metropolice/vo/allunitsmovein.wav" )
Schema.voice.AddVoice( combine, "Amputate", "Amputate.", "npc/metropolice/vo/amputate.wav" )
Schema.voice.AddVoice( combine, "Anti-Citizen", "Anti-citizen.", "npc/metropolice/vo/anticitizen.wav" )
Schema.voice.AddVoice( combine, "Citizen", "Citizen.", "npc/metropolice/vo/citizen.wav" )
Schema.voice.AddVoice( combine, "Copy", "Copy.", "npc/metropolice/vo/copy.wav" )
Schema.voice.AddVoice( combine, "Cover Me", "Cover me, I'm going in!", "npc/metropolice/vo/covermegoingin.wav" )
Schema.voice.AddVoice( combine, "Assist Trespass", "Assist for a criminal trespass!", "npc/metropolice/vo/criminaltrespass63.wav" )
Schema.voice.AddVoice( combine, "Destroy Cover", "Destroy that cover!", "npc/metropolice/vo/destroythatcover.wav" )
Schema.voice.AddVoice( combine, "Don't Move", "Don't move!", "npc/metropolice/vo/dontmove.wav" )
Schema.voice.AddVoice( combine, "Final Verdict", "Final verdict administered.", "npc/metropolice/vo/finalverdictadministered.wav" )
Schema.voice.AddVoice( combine, "Final Warning", "Final warning!", "npc/metropolice/vo/finalwarning.wav" )
Schema.voice.AddVoice( combine, "First Warning", "First warning, move away!", "npc/metropolice/vo/firstwarningmove.wav" )
Schema.voice.AddVoice( combine, "Get Down", "Get down!", "npc/metropolice/vo/getdown.wav" )
Schema.voice.AddVoice( combine, "Get Out", "Get out of here!", "npc/metropolice/vo/getoutofhere.wav" )
Schema.voice.AddVoice( combine, "Suspect One", "I got suspect one here.", "npc/metropolice/vo/gotsuspect1here.wav" )
Schema.voice.AddVoice( combine, "Help", "Help!", "npc/metropolice/vo/help.wav" )
Schema.voice.AddVoice( combine, "Running", "He's running!", "npc/metropolice/vo/hesrunning.wav" )
Schema.voice.AddVoice( combine, "Hold It", "Hold it right there!", "npc/metropolice/vo/holditrightthere.wav" )
Schema.voice.AddVoice( combine, "Move Along Repeat", "I said move along.", "npc/metropolice/vo/isaidmovealong.wav" )
Schema.voice.AddVoice( combine, "Malcompliance", "Issuing malcompliance citation.", "npc/metropolice/vo/issuingmalcompliantcitation.wav" )
Schema.voice.AddVoice( combine, "Keep Moving", "Keep moving!", "npc/metropolice/vo/keepmoving.wav" )
Schema.voice.AddVoice( combine, "Lock Position", "All units, lock your position!", "npc/metropolice/vo/lockyourposition.wav" )
Schema.voice.AddVoice( combine, "Trouble", "Lookin' for trouble?", "npc/metropolice/vo/lookingfortrouble.wav" )
Schema.voice.AddVoice( combine, "Look Out", "Look out!", "npc/metropolice/vo/lookout.wav" )
Schema.voice.AddVoice( combine, "Minor Hits", "Minor hits, continuing prosecution.", "npc/metropolice/vo/minorhitscontinuing.wav" )
Schema.voice.AddVoice( combine, "Move", "Move!", "npc/metropolice/vo/move.wav" )
Schema.voice.AddVoice( combine, "Move Along", "Move along!", "npc/metropolice/vo/movealong3.wav" )
Schema.voice.AddVoice( combine, "Move Back", "Move back, right now!", "npc/metropolice/vo/movebackrightnow.wav" )
Schema.voice.AddVoice( combine, "Move It", "Move it!", "npc/metropolice/vo/moveit2.wav" )
Schema.voice.AddVoice( combine, "Hardpoint", "Moving to hardpoint.", "npc/metropolice/vo/movingtohardpoint.wav" )
Schema.voice.AddVoice( combine, "Officer Help", "Officer needs help!", "npc/metropolice/vo/officerneedshelp.wav" )
Schema.voice.AddVoice( combine, "Privacy", "Possible level three civil privacy violator here!", "npc/metropolice/vo/possiblelevel3civilprivacyviolator.wav" )
Schema.voice.AddVoice( combine, "Judgement", "Suspect prepare to receive civil judgement!", "npc/metropolice/vo/prepareforjudgement.wav" )
Schema.voice.AddVoice( combine, "Priority Two", "I have a priority two anti-citizen here!", "npc/metropolice/vo/priority2anticitizenhere.wav" )
Schema.voice.AddVoice( combine, "Prosecute", "Prosecute!", "npc/metropolice/vo/prosecute.wav" )
Schema.voice.AddVoice( combine, "Amputate Ready", "Ready to amputate!", "npc/metropolice/vo/readytoamputate.wav" )
Schema.voice.AddVoice( combine, "Rodger That", "Rodger that!", "npc/metropolice/vo/rodgerthat.wav" )
Schema.voice.AddVoice( combine, "Search", "Search!", "npc/metropolice/vo/search.wav" )
Schema.voice.AddVoice( combine, "Shit", "Shit!", "npc/metropolice/vo/shit.wav" )
Schema.voice.AddVoice( combine, "Sentence Delivered", "Sentence delivered.", "npc/metropolice/vo/sentencedelivered.wav" )
Schema.voice.AddVoice( combine, "Sterilize", "Sterilize!", "npc/metropolice/vo/sterilize.wav" )
Schema.voice.AddVoice( combine, "Take Cover", "Take cover!", "npc/metropolice/vo/takecover.wav" )
Schema.voice.AddVoice( combine, "Restrict", "Restrict!", "npc/metropolice/vo/restrict.wav" )
Schema.voice.AddVoice( combine, "Restricted", "Restricted block.", "npc/metropolice/vo/restrictedblock.wav" )
Schema.voice.AddVoice( combine, "Second Warning", "This is your second warning!", "npc/metropolice/vo/thisisyoursecondwarning.wav" )
Schema.voice.AddVoice( combine, "Verdict", "You want a non-compliance verdict?", "npc/metropolice/vo/youwantamalcomplianceverdict.wav" )
Schema.voice.AddVoice( combine, "Backup", "Backup!", "npc/metropolice/vo/backup.wav" )
Schema.voice.AddVoice( combine, "Apply", "Apply.", "npc/metropolice/vo/apply.wav" )
Schema.voice.AddVoice( combine, "Restriction", "Terminal restriction zone.", "npc/metropolice/vo/terminalrestrictionzone.wav" )
Schema.voice.AddVoice( combine, "Complete", "Protection complete.", "npc/metropolice/vo/protectioncomplete.wav" )
Schema.voice.AddVoice( combine, "Location Unknown", "Suspect location unknown.", "npc/metropolice/vo/suspectlocationunknown.wav" )
Schema.voice.AddVoice( combine, "Can 1", "Pick up that can.", "npc/metropolice/vo/pickupthecan1.wav" )
Schema.voice.AddVoice( combine, "Can 2", "Pick... up... the can.", "npc/metropolice/vo/pickupthecan2.wav" )
Schema.voice.AddVoice( combine, "Wrap It", "That's it, wrap it up.", "npc/combine_soldier/vo/thatsitwrapitup.wav" )
Schema.voice.AddVoice( combine, "Can 3", "I said pickup the can!", "npc/metropolice/vo/pickupthecan3.wav" )
Schema.voice.AddVoice( combine, "Can 4", "Now, put it in the trash can.", "npc/metropolice/vo/putitinthetrash1.wav" )
Schema.voice.AddVoice( combine, "Can 5", "I said put it in the trash can!", "npc/metropolice/vo/putitinthetrash2.wav" )
Schema.voice.AddVoice( combine, "Now Get Out", "Now get out of here!", "npc/metropolice/vo/nowgetoutofhere.wav" )
Schema.voice.AddVoice( combine, "Haha", "Haha.", "npc/metropolice/vo/chuckle.wav" )
Schema.voice.AddVoice( combine, "X-Ray", "X-Ray!", "npc/metropolice/vo/xray.wav" )
Schema.voice.AddVoice( combine, "Patrol", "Patrol!", "npc/metropolice/vo/patrol.wav" )
Schema.voice.AddVoice( combine, "Serve", "Serve.", "npc/metropolice/vo/serve.wav" )
Schema.voice.AddVoice( combine, "Knocked Over", "You knocked it over, pick it up!", "npc/metropolice/vo/youknockeditover.wav" )
Schema.voice.AddVoice( combine, "Watch It", "Watch it!", "npc/metropolice/vo/watchit.wav" )
Schema.voice.AddVoice( combine, "Restricted Canals", "Suspect is using restricted canals at...", "npc/metropolice/vo/suspectusingrestrictedcanals.wav" )
Schema.voice.AddVoice( combine, "505", "Subject is five-oh-five!", "npc/metropolice/vo/subjectis505.wav" )
Schema.voice.AddVoice( combine, "404", "Possible four-zero-oh here!", "npc/metropolice/vo/possible404here.wav" )
Schema.voice.AddVoice( combine, "Vacate", "Vacate citizen!", "npc/metropolice/vo/vacatecitizen.wav" )
Schema.voice.AddVoice( combine, "Escapee", "Priority two escapee.", "npc/combine_soldier/vo/prioritytwoescapee.wav" )
Schema.voice.AddVoice( combine, "Objective", "Priority one objective.", "npc/combine_soldier/vo/priority1objective.wav" )
Schema.voice.AddVoice( combine, "Payback", "Payback.", "npc/combine_soldier/vo/payback.wav" )
Schema.voice.AddVoice( combine, "Got Him Now", "Affirmative, we got him now.", "npc/combine_soldier/vo/affirmativewegothimnow.wav" )
Schema.voice.AddVoice( combine, "Antiseptic", "Antiseptic.", "npc/combine_soldier/vo/antiseptic.wav" )
Schema.voice.AddVoice( combine, "Cleaned", "Cleaned.", "npc/combine_soldier/vo/cleaned.wav" )
Schema.voice.AddVoice( combine, "Engaged Cleanup", "Engaged in cleanup.", "npc/combine_soldier/vo/engagedincleanup.wav" )
Schema.voice.AddVoice( combine, "Engaging", "Engaging.", "npc/combine_soldier/vo/engaging.wav" )
Schema.voice.AddVoice( combine, "Full Response", "Executing full response.", "npc/combine_soldier/vo/executingfullresponse.wav" )
Schema.voice.AddVoice( combine, "Heavy Resistance", "Overwatch advise, we have heavy resistance.", "npc/combine_soldier/vo/heavyresistance.wav" )
Schema.voice.AddVoice( combine, "Inbound", "Inbound.", "npc/combine_soldier/vo/inbound.wav" )
Schema.voice.AddVoice( combine, "Lost Contact", "Lost contact!", "npc/combine_soldier/vo/lostcontact.wav" )
Schema.voice.AddVoice( combine, "Move In", "Move in!", "npc/combine_soldier/vo/movein.wav" )
Schema.voice.AddVoice( combine, "Harden Position", "Harden that position!", "npc/combine_soldier/vo/hardenthatposition.wav" )
Schema.voice.AddVoice( combine, "Go Sharp", "Go sharp, go sharp!", "npc/combine_soldier/vo/gosharpgosharp.wav" )
Schema.voice.AddVoice( combine, "Delivered", "Delivered.", "npc/combine_soldier/vo/delivered.wav" )
Schema.voice.AddVoice( combine, "Necrotics Inbound", "Necrotics, inbound!", "npc/combine_soldier/vo/necroticsinbound.wav" )
Schema.voice.AddVoice( combine, "Necrotics", "Necrotics.", "npc/combine_soldier/vo/necrotics.wav" )
Schema.voice.AddVoice( combine, "Outbreak", "Outbreak!", "npc/combine_soldier/vo/outbreak.wav" )
Schema.voice.AddVoice( combine, "Copy That", "Copy that.", "npc/combine_soldier/vo/copythat.wav" )
Schema.voice.AddVoice( combine, "Outbreak Status", "Outbreak status is code.", "npc/combine_soldier/vo/outbreakstatusiscode.wav" )
Schema.voice.AddVoice( combine, "Overwatch", "Overwatch!", "npc/combine_soldier/vo/overwatch.wav" )
Schema.voice.AddVoice( combine, "Preserve", "Preserve!", "npc/metropolice/vo/preserve.wav" )
Schema.voice.AddVoice( combine, "Pressure", "Pressure!", "npc/metropolice/vo/pressure.wav" )
Schema.voice.AddVoice( combine, "Phantom", "Phantom!", "npc/combine_soldier/vo/phantom.wav" )
Schema.voice.AddVoice( combine, "Stinger", "Stinger!", "npc/combine_soldier/vo/stinger.wav" )
Schema.voice.AddVoice( combine, "Shadow", "Shadow!", "npc/combine_soldier/vo/shadow.wav" )
Schema.voice.AddVoice( combine, "Savage", "Savage!", "npc/combine_soldier/vo/savage.wav" )
Schema.voice.AddVoice( combine, "Reaper", "Reaper!", "npc/combine_soldier/vo/reaper.wav" )
Schema.voice.AddVoice( combine, "Victor", "Victor!", "npc/metropolice/vo/victor.wav" )
Schema.voice.AddVoice( combine, "Sector", "Sector!", "npc/metropolice/vo/sector.wav" )
Schema.voice.AddVoice( combine, "Inject", "Inject!", "npc/metropolice/vo/inject.wav" )
Schema.voice.AddVoice( combine, "Dagger", "Dagger!", "npc/combine_soldier/vo/dagger.wav" )
Schema.voice.AddVoice( combine, "Blade", "Blade!", "npc/combine_soldier/vo/blade.wav" )
Schema.voice.AddVoice( combine, "Razor", "Razor!", "npc/combine_soldier/vo/razor.wav" )
Schema.voice.AddVoice( combine, "Nomad", "Nomad!", "npc/combine_soldier/vo/nomad.wav" )
Schema.voice.AddVoice( combine, "Judge", "Judge!", "npc/combine_soldier/vo/judge.wav" )
Schema.voice.AddVoice( combine, "Ghost", "Ghost!", "npc/combine_soldier/vo/ghost.wav" )
Schema.voice.AddVoice( combine, "Sword", "Sword!", "npc/combine_soldier/vo/sword.wav" )
Schema.voice.AddVoice( combine, "Union", "Union!", "npc/metropolice/vo/union.wav" )
Schema.voice.AddVoice( combine, "Helix", "Helix!", "npc/combine_soldier/vo/helix.wav" )
Schema.voice.AddVoice( combine, "Storm", "Storm!", "npc/combine_soldier/vo/storm.wav" )
Schema.voice.AddVoice( combine, "Spear", "Spear!", "npc/combine_soldier/vo/spear.wav" )
Schema.voice.AddVoice( combine, "Vamp", "Vamp!", "npc/combine_soldier/vo/vamp.wav" )
Schema.voice.AddVoice( combine, "Nova", "Nova!", "npc/combine_soldier/vo/nova.wav" )
Schema.voice.AddVoice( combine, "Mace", "Mace!", "npc/combine_soldier/vo/mace.wav" )
Schema.voice.AddVoice( combine, "Grid", "Grid!", "npc/combine_soldier/vo/grid.wav" )
Schema.voice.AddVoice( combine, "Kilo", "Kilo!", "npc/combine_soldier/vo/kilo.wav" )
Schema.voice.AddVoice( combine, "Echo", "Echo!", "npc/combine_soldier/vo/echo.wav" )
Schema.voice.AddVoice( combine, "Dash", "Dash!", "npc/combine_soldier/vo/dash.wav" )
Schema.voice.AddVoice( combine, "Apex", "Apex!", "npc/combine_soldier/vo/apex.wav" )
Schema.voice.AddVoice( combine, "Jury", "Jury!", "npc/metropolice/vo/jury.wav" )
Schema.voice.AddVoice( combine, "King", "King!", "npc/metropolice/vo/king.wav" )
Schema.voice.AddVoice( combine, "Lock", "Lock!", "npc/metropolice/vo/lock.wav" )
Schema.voice.AddVoice( combine, "Vice", "Vice!", "npc/metropolice/vo/vice.wav" )
Schema.voice.AddVoice( combine, "Zero", "Zero!", "npc/metropolice/vo/zero.wav" )
Schema.voice.AddVoice( combine, "Zone", "Zone!", "npc/metropolice/vo/zone.wav" )